#!/bin/bash

# Fix 1: useReaderController.ts exhaustive-deps warning
sed -i 's/\[readerViewMode, currentTheme, customTheme, fontFamily, fontSize, lineHeight, fontProfiles, shouldForceFont, bookId, dispatchCompass, bookMetadata, initialLocation, getInitialLocation, coldOpenGuard, setCurrentSection\]/\[readerViewMode, currentTheme, customTheme, fontFamily, fontSize, lineHeight, fontProfiles, shouldForceFont, dispatchCompass, bookMetadata, initialLocation, getInitialLocation, coldOpenGuard, setCurrentSection\]/g' src/app/reader/useReaderController.ts

# Wait, let's just do it with search-and-replace using perl
perl -0777 -pi -e 's/(onBookLoaded: \(_book\) => \{\s+\/\/ Indexing is now deferred until search is opened\s+\},\s+onClick: \(e: MouseEvent\) => \{\s+const selection = e\.view\?\.getSelection\(\);\s+if \(\!selection \|\| selection\.isCollapsed\) \{\s+useReaderUIStore\.getState\(\)\.dispatchCompass\(\{ type: '\''OUTSIDE_TAP'\'' \}\);\s+\}\s+\},\s+onError: \(msg\) => \{\s+logger\.error\('\''Reader Error:'\'', msg\);\s+\},\s+\}\), \[\s+readerViewMode,\s+currentTheme,\s+customTheme,\s+fontFamily,\s+fontSize,\s+lineHeight,\s+fontProfiles,\s+shouldForceFont,\s+bookId,\s+dispatchCompass,\s+bookMetadata,\s+initialLocation,\s+getInitialLocation,\s+coldOpenGuard,\s+setCurrentSection,\s+\]\);)/onBookLoaded: (_book) => {\n      \/\/ Indexing is now deferred until search is opened\n    },\n    onClick: (e: MouseEvent) => {\n      const selection = e.view?.getSelection();\n      if (!selection || selection.isCollapsed) {\n        useReaderUIStore.getState().dispatchCompass({ type: '\''OUTSIDE_TAP'\'' });\n      }\n    },\n    onError: (msg) => {\n      logger.error('\''Reader Error:'\'', msg);\n    },\n  }), [\n    readerViewMode,\n    currentTheme,\n    customTheme,\n    fontFamily,\n    fontSize,\n    lineHeight,\n    fontProfiles,\n    shouldForceFont,\n    dispatchCompass,\n    bookMetadata,\n    initialLocation,\n    getInitialLocation,\n    coldOpenGuard,\n    setCurrentSection,\n  ]);/s' src/app/reader/useReaderController.ts

# Fix 2: React refresh warnings (extract non-components)
# Well, wait, the react refresh warnings are mostly about module exports
# For routes.tsx, ConfirmDialog.tsx, ReaderCommands.tsx we can either move them or add eslint-disable-next-line
