/**
 * Registry-driven documentation renderers (Phase 9 docs item; master plan
 * §4 rule 10 — "AGENTS.md is generated from one canonical TESTING.md and
 * the registries").
 *
 * PURE renderers — no filesystem access here. The drift gate
 * (`src/app/docs/docs.test.ts`) gathers the inputs that come from the tree
 * (TESTING.md text, tsconfig path aliases), asserts the authored maps in
 * this module match the filesystem, and — with `REGEN_DOCS=1` — writes the
 * rendered files. `npm run docs:generate` is the operator entry point; a
 * plain `npm test` FAILS when any generated doc drifts from the registries.
 *
 * Generated files:
 *   - architecture.md          (end-state module map, C1–C12, rules, formats)
 *   - AGENTS.md                (PR gate from TESTING.md + working agreement)
 *   - src/kernel/README.md     (kernel admission rule + module table + egress)
 *   - src/data/README.md       (IDB schema/migrations/repos from src/data/schema.ts)
 *   - src/domains/README.md    (domain modules + import discipline)
 *   (src/store/README.md is generated by its own gate:
 *    src/store/__tests__/registry.test.ts / REGEN_STORE_DOCS=1.)
 */
import { EGRESS_DESTINATIONS } from '@kernel/net/destinations';
import { PROVIDERS, type ProviderDescriptor } from '@lib/tts/providers/registry';
import { STORE_REGISTRY } from '@store/registry';
import { CURRENT_SCHEMA_VERSION } from '@store/yjs-provider';
import { DB_NAME, DB_VERSION, MIGRATIONS } from '@data/schema';
import { SETTINGS_PANELS } from '../settings/registry';
import { BOOT_PHASES, type BootPhase } from '../bootstrap';
import { CRDT_MIGRATIONS } from '../migrations';

// ---------------------------------------------------------------------------
// Shared rendering helpers
// ---------------------------------------------------------------------------

function generatedBanner(): string {
  return [
    '<!-- GENERATED FILE — do not edit by hand. -->',
    '<!-- Rendered by src/app/docs/registryDocs.ts from the live registries. -->',
    '<!-- Drift-gated by src/app/docs/docs.test.ts: a plain `npm test` fails when -->',
    '<!-- this file disagrees with the registries. Regenerate: npm run docs:generate -->',
    '',
  ].join('\n');
}

function mdTable(headers: readonly string[], rows: readonly (readonly string[])[]): string {
  const line = (cells: readonly string[]) => `| ${cells.join(' | ')} |`;
  return [line(headers), line(headers.map(() => '---')), ...rows.map(line)].join('\n');
}

// ---------------------------------------------------------------------------
// The module map (completeness-gated against the filesystem by docs.test.ts)
// ---------------------------------------------------------------------------

/** src/* directories — gated: set equality with the directories on disk. */
export const SRC_MODULES: Readonly<Record<string, string>> = {
  kernel: 'L0 — imports nothing internal (admission: zero deps + ≥2 consumers, C12)',
  data: 'L1 — the ONLY IndexedDB subsystem (rule 2; see src/data/README.md)',
  store: 'L2 — three-tier store registry + Y.Doc provider (see src/store/README.md)',
  domains: 'L3 — vertical feature modules (rule 3; see src/domains/README.md)',
  lib: 'legacy-geography keepers — incl. the AUDIO domain at lib/tts/ (engine, providers, pipeline) and app services (Backup, Maintenance, ingestion, sanitizer)',
  app: 'L4 — composition root: bootstrap + boot tasks, CRDT migration coordinator, routes, settings registry, controllers, port adapters, repositories',
  components: 'React UI by feature area (library, reader, settings, sync, chinese, ui design system)',
  hooks: 'shared React hooks (useEpubReader + reader/sync/TTS hooks)',
  layouts: 'RootLayout — the router shell (toasts/confirm/announcer live ABOVE the route gate)',
  types: 'L0 types layer — db.ts dissolved by domain (P1); types-imports-nothing at 0',
  assets: 'static imports (icons, images)',
  test: 'vitest setup + typed harness + fixtures (see TESTING.md)',
  verification: 'in-vitest characterization ports of two E2E journeys (drive sync, background crash)',
  workers: 'worker entries (search, TTS) — import closures asserted by the worker-chunk check',
};

/** src/domains/* — gated: set equality with the directories on disk. */
export const DOMAIN_MODULES: Readonly<Record<string, string>> = {
  chinese: 'pinyin geometry engine, dictionary (separate versicle-dict IDB), vocabulary',
  google: 'GoogleAuthClient (per-service tokens), DriveClient, GenAIClient + per-feature zod modules',
  library: 'ImportOrchestrator job queue, LibraryService (keyed mutex), SHA-256 identity, reingest driver',
  reader: 'ReaderEngine port (EpubJsEngine = sole epubjs importer), overlays, session recorder',
  search: 'SearchSession over the search worker + persisted searchText repo',
  sync: 'SyncBackend port (Firestore or Mock), SyncOrchestrator, workspaces, typed SyncEvent bus',
};

/** src/kernel/* — gated: set equality with the directories on disk. */
export const KERNEL_MODULES: Readonly<Record<string, string>> = {
  cfi: 'canonical CFI algebra — parse, contains, group, merge, locale-aware sentence snap',
  diagnostics: 'flight-recorder ring-buffer core (namespaced buffers per subsystem)',
  locale: 'typed MessageKey catalog, cached Intl formatters, LiveAnnouncer, uiLocale',
  net: 'NetworkGateway + egress destination registry + generated-CSP renderer',
};

/** Entry files — gated: existence on disk. */
export const ENTRY_FILES: Readonly<Record<string, string>> = {
  'src/main.tsx': 'thin entry — installs the test API (DEV/E2E), mounts <App/>',
  'src/App.tsx': 'boot-state rendering + router gate over app/routes.tsx',
  'src/sw.ts': 'service worker — workbox precache, runtime caching, SKIP_WAITING handshake',
  'src/test-api.ts': 'window.__versicleTest page-side seams (DEV/VITE_E2E builds only)',
};

/** Repo-root directories named in the docs — gated: existence on disk. */
export const ROOT_DIRS: Readonly<Record<string, string>> = {
  'verification/': 'Playwright journey suite (Docker lane; see TESTING.md)',
  'scripts/': 'operator tooling: gates, generators, codemods, fixture capture (scripts/README.md)',
  'third-party/': 'vendored runtime artifacts (piper) + the license inventory',
  'docs/adr/': 'architecture decision records (i18n strategy, android-backup)',
  'plan/overhaul/': 'the overhaul program: master plan, analyses, prep docs, close-out',
};

function renderModuleTree(): string {
  const pad = (label: string, width: number) => label.padEnd(width);
  const lines: string[] = [];
  lines.push('src/');
  const srcOrder = [
    'kernel', 'data', 'store', 'domains', 'lib', 'app', 'components',
    'hooks', 'layouts', 'types', 'assets', 'test', 'verification', 'workers',
  ];
  for (const name of srcOrder) {
    lines.push(`  ${pad(`${name}/`, 25)}# ${SRC_MODULES[name]}`);
    if (name === 'kernel') {
      for (const [sub, desc] of Object.entries(KERNEL_MODULES)) {
        lines.push(`    ${pad(`${sub}/`, 23)}# ${desc}`);
      }
    }
    if (name === 'domains') {
      for (const [sub, desc] of Object.entries(DOMAIN_MODULES)) {
        lines.push(`    ${pad(`${sub}/`, 23)}# ${desc}`);
      }
    }
  }
  for (const [file, desc] of Object.entries(ENTRY_FILES)) {
    lines.push(`  ${pad(file.replace(/^src\//, ''), 25)}# ${desc}`);
  }
  return lines.join('\n');
}

/** Exported so the gate can assert the curated order covers SRC_MODULES. */
export function srcModuleOrderForTest(): readonly string[] {
  return [
    'kernel', 'data', 'store', 'domains', 'lib', 'app', 'components',
    'hooks', 'layouts', 'types', 'assets', 'test', 'verification', 'workers',
  ];
}

// ---------------------------------------------------------------------------
// C1–C12 contract inventory (file pointers existence-gated by docs.test.ts)
// ---------------------------------------------------------------------------

export interface ContractRow {
  id: string;
  name: string;
  /** Where the contract lives (file pointers, existence-gated). */
  home: readonly string[];
  /** Runtime validation / versioning posture, one line. */
  posture: string;
  /** The pinning suites / gates (file pointers, existence-gated). */
  pinnedBy: readonly string[];
}

export const CONTRACTS: readonly ContractRow[] = [
  {
    id: 'C1',
    name: 'IndexedDB storage schema',
    home: ['src/data/schema.ts'],
    posture: `zod rows in src/data/rows/; append-only versioned migration registry (DB v${DB_VERSION})`,
    pinnedBy: ['src/data/migrations.test.ts', 'src/data/connection.test.ts', 'src/data/__fixtures__/schema-fixtures.ts'],
  },
  {
    id: 'C2',
    name: 'CRDT document schema',
    home: ['src/store/registry.ts', 'src/app/migrations.ts'],
    posture: `syncedKeys whitelist + merge-defaults hydration; coordinator chain at v${CURRENT_SCHEMA_VERSION}; doc-level quarantine on the meta map`,
    pinnedBy: ['src/store/__tests__/crdt-contract/fixtures-manifest.test.ts', 'src/store/__tests__/crdt-contract/fixtures-hydration.test.ts', 'src/store/__tests__/crdt-contract/migrations.test.ts', 'src/test/fixtures/ydoc/manifest.json'],
  },
  {
    id: 'C3',
    name: 'Sync transport (SyncBackend)',
    home: ['src/domains/sync/backend/SyncBackend.ts'],
    posture: 'one behavioral spec, two transports (mock on every run, Firestore emulator gated); observe-mode zod on inbound docs',
    pinnedBy: ['src/lib/sync/syncBackendContract.ts', 'src/lib/sync/syncBackendContract.mock.test.ts', 'src/lib/sync/syncBackendContract.emulator.test.ts'],
  },
  {
    id: 'C4',
    name: 'TTS engine RPC',
    home: ['src/lib/tts/engine/TtsEngine.ts', 'src/lib/tts/engine/WorkerTtsEngine.ts'],
    posture: 'single monotonic PlaybackSnapshot{seq} channel; 23 parity scenarios × 2 transports',
    pinnedBy: ['src/lib/tts/engine/engineParityScenarios.ts', 'src/lib/tts/engine/engineParity.inprocess.test.ts', 'src/lib/tts/engine/engineParity.worker.test.ts'],
  },
  {
    id: 'C5',
    name: 'TTS provider plugin interface',
    home: ['src/lib/tts/providers/types.ts', 'src/lib/tts/providers/registry.ts'],
    posture: `ProviderDescriptor registry (${PROVIDERS.length} providers); reject-only play(), typed ProviderPlaybackError`,
    pinnedBy: ['src/lib/tts/providers/describeProviderContract.ts'],
  },
  {
    id: 'C6',
    name: 'Store/selector public API',
    home: ['src/store/registry.ts', 'src/store/yjs-provider.ts'],
    posture: 'three declared tiers; synced stores created only via defineSyncedStore; generated README',
    pinnedBy: ['src/store/__tests__/registry.test.ts'],
  },
  {
    id: 'C7',
    name: 'Reader engine port',
    home: ['src/domains/reader/engine/ReaderEngine.ts'],
    posture: 'renderer-agnostic port; EpubJsEngine is the sole runtime epubjs importer (lint error)',
    pinnedBy: ['src/domains/reader/engine/ReaderEngine.contract.test.ts'],
  },
  {
    id: 'C8',
    name: 'Ingestion artifact contract',
    home: ['src/lib/ingestion/sentence-extraction.ts', 'src/domains/library/import/extract.ts'],
    posture: 'raw-at-rest extraction v3; CFI-comparison fixtures gate any extractionVersion bump; one extractBook()',
    pinnedBy: ['src/lib/ingestion/sentence-extraction.test.ts', 'src/lib/ingestion/extractSentences.test.ts', 'src/domains/library/import/extract.test.ts', 'src/domains/library/reingest.test.ts'],
  },
  {
    id: 'C9',
    name: 'External egress contract',
    home: ['src/kernel/net/destinations.ts', 'src/kernel/net/NetworkGateway.ts'],
    posture: `${EGRESS_DESTINATIONS.length} destinations with data class/consent/timeout; CSP GENERATED from the registry (scripts/generate-csp.mjs)`,
    pinnedBy: ['src/kernel/net/csp.test.ts', 'src/kernel/net/NetworkGateway.test.ts'],
  },
  {
    id: 'C10',
    name: 'Error contract',
    home: ['src/types/errors.ts', 'src/app/errors/presentError.ts'],
    posture: 'AppError taxonomy; append-only code namespaces; presentError is the one user-facing mapper',
    pinnedBy: ['src/types/errors.test.ts'],
  },
  {
    id: 'C11',
    name: 'Boot contract',
    home: ['src/app/bootstrap.ts', 'src/app/boot/registerBootTasks.ts'],
    posture: `${BOOT_PHASES.length} phases, sequential awaited tasks; halt() for migration confirmation; SafeMode on throw`,
    pinnedBy: ['src/App_Boot.test.tsx', 'src/App_MigrationFailure.test.tsx', 'src/App_SW_Wait.test.tsx', 'src/App_Capacitor.test.tsx'],
  },
  {
    id: 'C12',
    name: 'Layering & worker-purity contract',
    home: ['.dependency-cruiser.cjs', '.dependency-cruiser.runtime.cjs', 'eslint.config.js'],
    posture: 'compile-time direction via tsc -b project references; emitted-artifact ground truth via the five-check build gate',
    pinnedBy: ['scripts/check-worker-chunk.mjs', 'scripts/depcruise-baseline.mjs', 'scripts/assert-single-instance.cjs', 'src/store/__tests__/crdt-contract/single-yjs-instance.test.ts'],
  },
];

// ---------------------------------------------------------------------------
// Boundary rules (master plan §2) — end-state enforcement table
// (authored from plan/overhaul/prep/phase9-close.md §3; pointers gated)
// ---------------------------------------------------------------------------

export interface BoundaryRuleRow {
  n: number;
  rule: string;
  mechanism: string;
  level: 'error' | 'error + ratchet' | 'ratchet' | 'process' | 'partial';
  exceptions: string;
  pointers: readonly string[];
}

export const BOUNDARY_RULES: readonly BoundaryRuleRow[] = [
  {
    n: 1,
    rule: 'kernel/ imports nothing internal; admission = zero deps + ≥2 consumers',
    mechanism: 'depcruise `kernel-imports-nothing` + `types-imports-nothing`, both error at 0',
    level: 'error',
    exceptions: '`~types` is the one sanctioned dependency (named in the rule itself)',
    pointers: ['.dependency-cruiser.cjs'],
  },
  {
    n: 2,
    rule: 'All IndexedDB via data/ repos; readwrite + `idb` banned elsewhere',
    mechanism: 'eslint `idb`-import ban (prod AND tests) + `readwrite`-literal syntactic ban, error; depcruise `data-no-upward` error at 0; the write-gate\'s synchronous-callback API structurally bans intra-transaction awaits',
    level: 'error',
    exceptions: 'none — schema fixtures live inside src/data/__fixtures__/',
    pointers: ['eslint.config.js', 'src/data/write-gate.ts'],
  },
  {
    n: 3,
    rule: 'Domain services import kernel+data+own module+other domains\' index only, never store/',
    mechanism: 'depcruise `domains-no-store` error at 0',
    level: 'error',
    exceptions: 'ONE carve-out: store/yjs-provider.ts for the relocated CheckpointService/Inspector live Y.Doc handles',
    pointers: ['.dependency-cruiser.cjs'],
  },
  {
    n: 4,
    rule: 'Domain ui/ reads via published hooks; writes via services/controllers',
    mechanism: 'store-registry README + projection-port pattern (libraryViewStore et al.); review-enforced',
    level: 'process',
    exceptions: 'no mechanical lint (a setter-import ban cannot tell reads from writes); residual ~70 `.getState()` sites outside store/+app/ are event-handler reads + injected port handles',
    pointers: ['src/store/README.md'],
  },
  {
    n: 5,
    rule: '`getState()` outside store/+app/ is an error',
    mechanism: 'structural, via the import graph: `domains-no-store` error at 0; `lib-not-to-store` ratchet 54→19 frozen edges',
    level: 'error + ratchet',
    exceptions: 'the 19 baseline-frozen lib/ edges (legacy geography: lib/tts engine context, LexiconService, BackupService, …)',
    pointers: ['.dependency-cruiser-baseline.json'],
  },
  {
    n: 6,
    rule: 'Worker import closure free of zustand/yjs/store',
    mechanism: 'check:worker-chunk check 1 (emitted-chunk closure) in the build gate; `consistent-type-imports` error; depcruise `no-circular` + `no-circular-runtime` error at 0',
    level: 'error + ratchet',
    exceptions: '`worker-no-state-typegraph` stays a ratchet at 16 type-only edges (hazard meter; the chunk check is the hard floor)',
    pointers: ['scripts/check-worker-chunk.mjs', '.dependency-cruiser.runtime.cjs'],
  },
  {
    n: 7,
    rule: 'All egress via NetworkGateway.egress(); CSP generated from the registry',
    mechanism: 'syntactic fetch/XHR/sendBeacon bans at error; CSP rendered by scripts/generate-csp.mjs; registry==CSP pinned by csp.test.ts',
    level: 'error',
    exceptions: 'ONE carve-out: src/kernel/net/** (the gateway itself); tests share it',
    pointers: ['scripts/generate-csp.mjs', 'src/kernel/net/csp.test.ts'],
  },
  {
    n: 8,
    rule: 'epubjs only in the reader engine; synthesis SDKs only in providers; singletons only in app/; no module-scope side effects outside bootstrap',
    mechanism: 'runtime-epubjs import ban at error (type-only legal) with named carve-outs; piper vendored behind PiperRuntime; C11 entry-gate boot tests',
    level: 'error',
    exceptions: 'three named epubjs carve-outs (engine dir incl. offscreen/, kernel epubcfiShim, library extract.ts per C8); singleton/side-effect halves rest on the C11 contract + review',
    pointers: ['eslint.config.js', 'src/kernel/cfi/epubcfiShim.ts', 'src/domains/library/import/extract.ts'],
  },
  {
    n: 9,
    rule: 'Mock seams reachable only from the composition root behind DEV/VITE_E2E',
    mechanism: 'check:worker-chunk check 2: no MockBackend/MockFireProvider/MockGenAIClient source in ANY production chunk',
    level: 'error',
    exceptions: 'none',
    pointers: ['scripts/check-worker-chunk.mjs'],
  },
  {
    n: 10,
    rule: 'TS project references per layer + all test code typechecked',
    mechanism: '`tsc -b` solution build: app + test + e2e + node + 3 vendored packages',
    level: 'partial',
    exceptions: 'per-LAYER references NOT implemented (`composite` forces declaration emit, conflicting with the bundler-mode posture); dependency DIRECTION is enforced by the depcruise error rules instead — documented exception',
    pointers: ['tsconfig.json', 'tsconfig.test.json', 'tsconfig.e2e.json'],
  },
];

// ---------------------------------------------------------------------------
// Boot phases (Record<BootPhase, …> makes coverage a compile-time property)
// ---------------------------------------------------------------------------

const BOOT_PHASE_NOTES: Readonly<Record<BootPhase, string>> = {
  interceptMigration: 'workspace-migration interceptor — may halt boot for user confirmation or apply a staged swap',
  openDB: `open ${DB_NAME} through the versioned migration registry (v${DB_VERSION})`,
  startYjsPersistence: 'y-idb persistence for the workspace Y.Doc (no module-scope boot)',
  whenHydrated: 'IDB load + per-store hydration handles; static-metadata projection hydrates',
  migrations: `CRDT migration coordinator — checkpoint, transform, atomic bump (target v${CURRENT_SCHEMA_VERSION})`,
  syncInit: 'sync orchestration (skipped while a migration awaits user confirmation)',
  deviceRegistration: 'TTS engine init + device-mesh registration',
  backgroundTasks: 'device heartbeat, Drive auto-scan, audio-cache eviction, re-ingest wave, social login',
};

// ---------------------------------------------------------------------------
// architecture.md
// ---------------------------------------------------------------------------

function renderFormatChain(): string {
  // Anonymous `migrate: () => undefined` steps get the contextual name
  // 'migrate'; only real named transforms are rendered as code.
  const crdtRows = CRDT_MIGRATIONS.map((m) => [
    `v${m.from} → v${m.to}`,
    m.migrate.name && m.migrate.name !== 'migrate'
      ? `\`${m.migrate.name}\``
      : '*(pure version bump)*',
  ]);
  const idbRows = MIGRATIONS.map((m) => [`v${m.toVersion}`, `\`${m.migrate.name}\``]);
  const persisted = STORE_REGISTRY.filter((e) => e.tier === 'local-persisted').map(
    (e) => [`\`${e.module}\``, `\`${String(e.persistence)}\``],
  );
  return [
    `The CRDT document schema is at **v${CURRENT_SCHEMA_VERSION}** (\`CURRENT_SCHEMA_VERSION\`,`,
    'src/store/yjs-provider.ts). The coordinator chain (src/app/migrations.ts —',
    'checkpoint before, atomic transactional bump, loud-fail to SafeMode):',
    '',
    mdTable(['Step', 'Transform'], crdtRows),
    '',
    `The IndexedDB schema (\`${DB_NAME}\`) is at **v${DB_VERSION}** (\`DB_VERSION\`,`,
    'src/data/schema.ts). Versioned registry steps past the v24 baseline',
    '(append-only; released steps are persisted format):',
    '',
    mdTable(['Step', 'Transform'], idbRows),
    '',
    'localStorage (zustand/persist) stores:',
    '',
    mdTable(['Store', 'Key'], persisted),
    '',
    'Backups are manifest **v3** (validate-before-destroy, pre-restore',
    'checkpoint — src/lib/BackupService.ts; round-trip suite',
    'src/lib/BackupService.roundtrip.test.ts). The Chinese dictionary lives in',
    'its own `versicle-dict` IndexedDB (src/domains/chinese/dictionary/).',
  ].join('\n');
}

/** Live ratchet counters, read from the committed baselines by the gate. */
export interface RatchetSnapshot {
  /** Total frozen dependency-cruiser violations. */
  depcruiseTotal: number;
  /** The rules still above zero, as [rule, count] in baseline order. */
  depcruiseNonZero: readonly (readonly [string, number])[];
  /** Production `as any` + `: any` sites in the lint-debt allowlist. */
  lintDebtAnySites: number;
  /** Production eslint-disable directives in the lint-debt allowlist. */
  lintDebtDisables: number;
}

export function renderArchitectureMd(ratchets: RatchetSnapshot): string {
  const contractRows = CONTRACTS.map((c) => [
    c.id,
    c.name,
    c.home.map((h) => `\`${h}\``).join(', '),
    c.posture,
    c.pinnedBy.map((p) => `\`${p}\``).join(', '),
  ]);
  const ruleRows = BOUNDARY_RULES.map((r) => [
    String(r.n),
    r.rule,
    r.mechanism,
    r.level,
    r.exceptions,
  ]);
  const bootRows = BOOT_PHASES.map((p, i) => [String(i + 1), `\`${p}\``, BOOT_PHASE_NOTES[p]]);
  const egressRows = EGRESS_DESTINATIONS.map((d) => [
    `\`${d.id}\``,
    d.hosts.join(', '),
    d.via,
    d.dataClass,
    d.consent,
    d.timeoutMs === null ? 'unbounded (abortable)' : `${d.timeoutMs} ms`,
    d.offline,
  ]);
  const settingsRows = [...SETTINGS_PANELS]
    .sort((a, b) => a.order - b.order)
    .map((p) => [`\`${p.id}\``, String(p.order), `\`${p.labelKey}\``, p.danger ? 'yes' : '']);
  // Widen the `as const` tuple: optional fields (platforms) are absent from
  // some narrowed entry types.
  const providerRows = (PROVIDERS as readonly ProviderDescriptor[]).map((p) => [
    `\`${p.id}\``,
    p.displayName,
    p.kind,
    p.requiresApiKey ? 'yes' : 'no',
    p.platforms ? p.platforms.join(', ') : 'all',
    [p.capabilities.downloadableVoices ? 'downloadable voices' : '', p.capabilities.localeAware ? 'locale-aware' : '']
      .filter(Boolean)
      .join(', ') || '—',
  ]);
  const tierCount = (tier: string) => STORE_REGISTRY.filter((e) => e.tier === tier).length;
  const nonZeroSummary = ratchets.depcruiseNonZero
    .map(([rule, count]) => `\`${rule}\` ${count}`)
    .join(' + ');

  return `${generatedBanner()}
# Versicle Architecture

Versicle is a local-first, privacy-centric EPUB reader and audiobook player
that runs entirely in the browser (or as a Capacitor hybrid app). User data
lives in a Yjs CRDT persisted to IndexedDB and optionally synced through the
owner's own Firebase project (BYO-Firebase); books, caches, and derived
content live in IndexedDB; heavy work (TTS synthesis, search, extraction)
runs client-side, much of it in workers.

This document describes the **end state of the 2026 overhaul program**
(plan/overhaul/README.md — phases 0–9, PROGRAM COMPLETE). It is generated
from the code's own registries, so it cannot drift: the structure below IS
what the gates enforce. History and rationale live in the master plan; how
to verify changes lives in \`TESTING.md\`.

## 1. Module map (the modular-monolith geography, as built)

Layers L0–L4 only depend downward (enforced — see §3). Replacement code
landed at its final address during the strangler phases; \`lib/\` is the
honest residual: the audio domain and a set of app services whose internals
were rebuilt in place without the (pure-motion) relocation to
\`domains/audio/\` — see the close-out notes in the master plan.

\`\`\`
${renderModuleTree()}
\`\`\`

Other repo roots:

${mdTable(['Path', 'What it is'], Object.entries(ROOT_DIRS).map(([p, d]) => [`\`${p}\``, d]))}

## 2. The contract registry (C1–C12)

The program's governing artifact (plan/overhaul/proposals/contract-first.md;
operating rules in the master plan §3). A contract version bump requires a
matching contract-suite change in the same PR. Everything not in this table
is an internal and may be rewritten at will.

${mdTable(['Id', 'Contract', 'Home', 'Validation / versioning', 'Pinned by'], contractRows)}

## 3. Boundary rules and their enforcement (master plan §2, end state)

Levels: **error** = CI-blocking, zero undocumented exceptions; **ratchet** =
warn-severity with a frozen baseline that may only decrease; **process** =
review/test-enforced. Source audit: plan/overhaul/prep/phase9-close.md §3.

${mdTable(['#', 'Rule', 'Enforcement', 'Level', 'Named exceptions / residuals'], ruleRows)}

Ratchet counters (live, from the committed baselines): dependency-cruiser
total **${ratchets.depcruiseTotal}** (${nonZeroSummary}; every other rule at
error/0), lint-debt allowlist **${ratchets.lintDebtAnySites}** \`any\`-sites +
**${ratchets.lintDebtDisables}** disables (\`lint-debt-allowlist.json\`), coverage
floor \`coverage-baseline.json\`, bundle budget \`bundle-baseline.json\`.

## 4. Persisted formats (the format-change chain)

${renderFormatChain()}

## 5. Boot sequence (C11)

\`src/app/bootstrap.ts\` owns the order; subsystems register tasks via the
manifest \`src/app/boot/registerBootTasks.ts\` (the one file that may import
subsystem boot modules). Phases, in order:

${mdTable(['#', 'Phase', 'What runs'], bootRows)}

A task throw routes to SafeModeView; \`ctx.halt()\` stops the sequence (used
while a backup restore or staged workspace swap needs the page). Wipe hooks
(\`src/data/wipe.ts\`) are registered at manifest time so \`wipeAllData()\`
can stop the sync and Yjs writers it cannot import.

## 6. Network egress (C9)

Every destination the app may contact, from
\`src/kernel/net/destinations.ts\` (the CSP is generated from this table —
\`npm run generate:csp\`; \`src/kernel/net/csp.test.ts\` pins registry==CSP):

${mdTable(['Id', 'Hosts', 'Via', 'Data class', 'Consent', 'Timeout', 'Offline'], egressRows)}

\`via: 'sdk'\` rows (firebase, OAuth plugins) own their HTTP inside an SDK:
their hosts feed the CSP but calls cannot route through \`egress()\`.

## 7. Settings surface

\`src/app/settings/registry.ts\` — every tab is deep-linkable as
\`/settings/:tab\`; panels lazy-load on first activation:

${mdTable(['Tab', 'Order', 'Label key', 'Danger'], settingsRows)}

## 8. TTS providers (C5)

\`src/lib/tts/providers/registry.ts\` — the settings UI, id unions, and
construction all derive from this registry:

${mdTable(['Id', 'Name', 'Kind', 'API key', 'Platforms', 'Capabilities'], providerRows)}

## 9. State stores

${tierCount('synced')} synced (CRDT user data), ${tierCount('local-persisted')} local-persisted
(localStorage), ${tierCount('ephemeral')} ephemeral — declared in
\`src/store/registry.ts\` and documented in the generated
\`src/store/README.md\` (tier semantics, Y.Map bindings, hydration modes).

## 10. How this app is verified

\`TESTING.md\` is the one authoritative testing document (local gate, CI
lanes, Docker E2E, emulator suites, ratchet model). The test strategy's
spine is the contract tier: every dual-implementation seam in §2 carries a
shared behavioral spec run against all implementations.
`;
}

// ---------------------------------------------------------------------------
// AGENTS.md (generated from TESTING.md's local-gate table + the registries)
// ---------------------------------------------------------------------------

export interface GateRow {
  check: string;
  command: string;
  expectation: string;
}

/**
 * Parse the "## The local gate" table out of TESTING.md. Throws (failing
 * the gate test) when the section or table cannot be found — TESTING.md is
 * the canonical source and AGENTS.md must not silently go stale.
 */
export function parseLocalGateTable(testingMd: string): GateRow[] {
  const section = testingMd.split(/^## The local gate.*$/m)[1]?.split(/^## /m)[0];
  if (!section) throw new Error('TESTING.md: "## The local gate" section not found');
  const rows: GateRow[] = [];
  for (const line of section.split('\n')) {
    const m = line.match(/^\|(.+)\|(.+)\|(.+)\|$/);
    if (!m) continue;
    const [check, command, expectation] = [m[1], m[2], m[3]].map((s) => s.trim());
    if (check === 'Check' || /^-+$/.test(check.replace(/\s/g, ''))) continue;
    rows.push({ check, command, expectation });
  }
  if (rows.length < 5) throw new Error('TESTING.md: local-gate table parse found too few rows');
  return rows;
}

/**
 * The Jules README preamble rule — preserved VERBATIM across regenerations
 * (the one hand-written instruction this generator must never reword).
 */
export const JULES_README_RULE = `## Project README.md

Whenever you update the project \`README.md\` file, make sure to include as a preamble an explanation for what \`Google Jules\` is and that \`Versicle\` is an experimental project implemented almost entirely with \`Jules\`.`;

export function renderAgentsMd(gateRows: readonly GateRow[], aliasNames: readonly string[]): string {
  const gates = gateRows
    .map((r, i) => `${i + 1}. ${r.command} — ${r.expectation} *(${r.check})*`)
    .join('\n');
  const aliases = aliasNames.map((a) => `\`${a}\``).join(' ');
  return `${generatedBanner()}
# AGENTS.md — working agreement for AI agents

Versicle is maintained almost entirely by AI agents. These documents are the
instruction channel — when they drift from reality, agents faithfully
execute the drift. This file is therefore GENERATED from the canonical
sources (TESTING.md's gate table + the code registries) and drift-gated by
\`src/app/docs/docs.test.ts\`: if you need to change it, change the source
and run \`npm run docs:generate\`. If an instruction here still contradicts
the tree, fixing the source document is part of the task.

## Canonical documents

- **\`TESTING.md\`** (repo root) — the ONE authoritative testing document:
  every test/lint/typecheck/ratchet command, the E2E and emulator flows, and
  the program rules that govern tests. Do not duplicate its content; link
  to it. The PR-gate list below is rendered from its local-gate table.
- **\`architecture.md\`** — the end-state architecture, generated from the
  code's own registries (module map, C1–C12 contract inventory, boundary
  rules, persisted formats). Current by construction.
- **\`plan/overhaul/README.md\`** — the 2026 overhaul master plan
  (PROGRAM COMPLETE). Its §4 "Program rules" remain binding for every
  change; the close-out banner carries the operator hand-off list.
- **Module READMEs** — \`src/kernel/\`, \`src/data/\`, \`src/store/\`,
  \`src/domains/\` are generated (same gate); the rest are hand-written.

## Pull Request prerequisites — the gate

All of these must pass before a PR (what each one is: \`TESTING.md\`):

${gates}

Conditional additions:

- \`firestore.rules\` / \`storage.rules\` changed → run the emulator-gated
  rules suite (command in \`TESTING.md\` §Emulator-gated suites).
- User-visible changes → run the relevant Playwright journeys via Docker
  (below) and check the screenshots.
- Registries, TESTING.md's gate table, or generated docs affected →
  \`npm run docs:generate\` and commit the result (a plain \`npm test\`
  fails on drift, so you cannot forget silently).

## Playwright verification suite (E2E)

The suite is Playwright TypeScript specs in \`verification/*.spec.ts\` (the
old Python/pytest suite is long gone — never create \`.py\` tests). It runs
in Docker; arguments pass through to \`npx playwright test\`:

\`\`\`bash
# If you are Jules (or docker needs root), use the sudo wrapper:
./jules_run_verification.sh

# Otherwise:
./run_verification.sh                                      # desktop + mobile projects
./run_verification.sh verification/test_journey_library.spec.ts
./run_verification.sh --project=webkit                     # auto-serialized
\`\`\`

Rules for E2E work:

1. Tests are modeled as **user journeys**. To cover a new feature or bug
   fix, extend a suitable existing journey or add a new one — keep journeys
   focused, not marathon-length.
2. Record a screenshot in \`verification/screenshots/\` for key steps (use
   the \`captureScreenshot\` helper in \`verification/utils.ts\`).
3. Use the deterministic waits from \`verification/utils.ts\`
   (\`window.__versicleTest.flushPersistence()\` / \`resetApp\`) — never add
   \`waitForTimeout\` sleeps for persistence.
4. Timeouts are almost always caused by bugs or flakiness in code or test,
   rarely by genuine slowness. Increasing a timeout is a last resort.

## Android Docker tests

\`\`\`bash
sudo docker build -t versicle-android -f Dockerfile.android .
sudo docker run --rm versicle-android
\`\`\`

(\`Dockerfile.android.dockerignore\` exists so \`android/\` reaches this
build context — do not re-add \`android\` to it.)

## Docker

You need to use \`sudo\` to run docker.

## Program rules — the ones agents trip over most

From \`plan/overhaul/README.md\` §4 (all of §4 is binding):

1. **Regression tests go into owning suites.** A new regression test is a
   \`describe('regression: <what>')\` block inside the existing
   \`Foo.test.ts\` co-located with \`Foo.ts\` — NEVER a new one-off file
   (\`Foo_BugXyz.test.ts\`, \`Foo.repro.test.ts\`). A per-bug file may be
   deleted only in the same PR that lands its assertions as such a block
   (the test-absorption ledger).
2. **Ratchets never regress.** \`.dependency-cruiser-baseline.json\`,
   \`lint-debt-allowlist.json\`, \`coverage-baseline.json\`, and
   \`bundle-baseline.json\` counts only move in the good direction. Most
   boundary rules are already at **error with zero exceptions** — do not
   add violations; restructure the change instead. New lint/boundary
   tooling lands at warn with a committed baseline; a rule flips to error
   only at zero violations.
3. **One vitest config.** \`vitest.config.ts\` is the single source of test
   discovery. Never add a \`test\` block to \`vite.config.ts\` (vitest
   silently ignores it) and never add a second config.
4. **Test seams are typed and centralized.** Page-side E2E seams go into
   \`src/test-api.ts\` (\`window.__versicleTest\`), not new \`window.__*\`
   globals. Unit-test doubles come from \`src/test/harness/\` — do not
   hand-roll \`vi.mock\` piles for repos/stores (\`vi.mock\` is lint-banned
   in the engine/provider/data directories).
5. **Commit style:** Conventional Commits — \`type(scope): imperative
   subject\` ≤72 chars; body explains *why*. One logical change per commit.
6. **Cross-root imports use path aliases.** Importing across the top-level
   \`src/\` roots uses the alias, never \`../\` chains: ${aliases}
   (declared in \`tsconfig.app.json\` \`paths\`; mirrored in
   \`vite.config.ts\` AND \`vitest.config.ts\` \`resolve.alias\` — vitest
   does not read vite.config.ts — and in \`tsconfig.e2e.json\` for specs).
   \`types/\` is \`~types\` because TypeScript rejects \`@types/…\`
   specifiers (TS6137). Same-directory and within-subtree imports stay
   relative. Enforced at error severity by \`no-restricted-imports\`;
   bulk-fix with \`node scripts/codemod-aliases.mjs\`.
7. **Generated docs are never hand-edited.** \`architecture.md\`, this
   file, and the kernel/data/store/domains READMEs are rendered from the
   registries — edit \`src/app/docs/registryDocs.ts\` (or the registry the
   fact lives in, or \`TESTING.md\` for the gate table) and run
   \`npm run docs:generate\`.

${JULES_README_RULE}

## IndexedDB schema changes

The schema and its versioned migration registry live in
\`src/data/schema.ts\` (currently \`DB_VERSION = ${DB_VERSION}\`). Bumping it is a
user-data format change (master plan §4 rule 4): append a migration step —
never edit a released one — and extend the captured-fixture upgrade tests in
\`src/data/migrations.test.ts\`. E2E specs open \`${DB_NAME}\` without an
explicit version, so there are no hardcoded version numbers to chase.
`;
}

// ---------------------------------------------------------------------------
// src/kernel/README.md
// ---------------------------------------------------------------------------

export function renderKernelReadme(): string {
  const moduleRows = Object.entries(KERNEL_MODULES).map(([name, desc]) => [`\`${name}/\``, desc]);
  const egressRows = EGRESS_DESTINATIONS.map((d) => [
    `\`${d.id}\``,
    d.hosts.join(', '),
    d.via,
    d.dataClass,
    d.consent,
  ]);
  return `${generatedBanner()}
# Kernel (L0)

The bottom layer. **\`kernel/\` imports nothing internal** except
\`~types\` — enforced at error by the dependency-cruiser
\`kernel-imports-nothing\` rule (0 violations). Admission requires zero
internal dependencies AND at least two consuming domains (the
anti-junk-drawer rule, C12); additions are reviewed against that rule and
recorded here by regeneration.

${mdTable(['Module', 'Contents'], moduleRows)}

## The egress destination registry (C9)

\`net/destinations.ts\` is the single source of truth for what hosts this
app may contact. \`NetworkGateway.egress(destinationId, …)\` checks every
production fetch against it (raw fetch is lint-banned outside
\`src/kernel/net/\`), and the CSP is GENERATED from it
(\`npm run generate:csp\`; \`net/csp.test.ts\` pins registry==CSP).

${mdTable(['Id', 'Hosts', 'Via', 'Data class', 'Consent'], egressRows)}

Full per-destination detail (timeouts, offline policy, purpose strings)
lives in the registry module itself and in \`architecture.md\` §6.
`;
}

// ---------------------------------------------------------------------------
// src/data/README.md
// ---------------------------------------------------------------------------

/** src/data contents — gated: set equality with non-test entries on disk. */
export const DATA_MODULES: Readonly<Record<string, string>> = {
  '__fixtures__/': 'captured v18/v24 schema fixtures + builders for the migration suite',
  'repos/': 'the repository surface (below) — the only place transactions are opened',
  'rows/': 'zod row schemas per domain (app, backup, cache, static) — drift-guard anchors',
  'snapshot/': 'YjsSnapshotService — THE one snapshot/export/import mechanism for the Y.Doc',
  'connection.ts': 'hardened open: blocked/blocking/terminated handlers, retry-with-reset, storage.persist()',
  'covers.ts': 'shared coverUrl() for the SW-served cover endpoint',
  'errors.ts': 'handleDbError boundary mapping onto the C10 taxonomy',
  'schema.ts': 'store map + DB_VERSION + the append-only versioned migration registry (C1)',
  'sw-contract.ts': 'the service-worker read contract (cover serving; legacy pre-v18 fallback)',
  'wipe.ts': 'wipeAllData() behind a writer-stop hook registry (sync + Yjs register at boot)',
  'write-gate.ts': 'navigator.locks write gate spanning tabs + the TTS worker; synchronous-callback API',
};

/** src/data/repos contents — gated: set equality with non-test files on disk. */
export const DATA_REPOS: Readonly<Record<string, string>> = {
  'audioCache.ts': 'TTS audio cache rows + LRU eviction (by_lastAccessed index)',
  'bookContent.ts': 'static book content + derived content replacement (ingest path)',
  'checkpoints.ts': 'pre-danger Y.Doc checkpoints (used by backup/restore/migrations)',
  'diagnostics.ts': 'flight-recorder persistence',
  'dictionary.ts': 'the separate versicle-dict database (Chinese dictionary)',
  'playbackCache.ts': 'session/playback cache (WebKit-safe write pattern preserved verbatim)',
  'searchText.ts': 'persisted search corpus (cache_search_text)',
};

export function renderDataReadme(): string {
  const idbRows = MIGRATIONS.map((m) => [`v${m.toVersion}`, `\`${m.migrate.name}\``]);
  return `${generatedBanner()}
# Data (L1) — the only IndexedDB subsystem

Rule 2 of the master plan §2, enforced at **error** with zero exceptions:
all IndexedDB access goes through this directory's repos; \`'readwrite'\`
transaction literals and \`idb\` imports are lint-banned everywhere else
(production AND tests). Writes additionally pass the navigator.locks
**write gate** (\`write-gate.ts\`), whose synchronous-callback API makes an
\`await\` inside a transaction unrepresentable — the WebKit-hang discipline
is structural.

The database is \`${DB_NAME}\` at **v${DB_VERSION}** (\`schema.ts\`). Migration
steps are append-only registry entries; the steps past the v24 baseline:

${mdTable(['Step', 'Transform'], idbRows)}

Captured-fixture upgrades (v18, v24 → current) are pinned in
\`migrations.test.ts\`; multi-tab upgrade behavior in \`connection.test.ts\`.

## Contents

${mdTable(['Entry', 'What it is'], Object.entries(DATA_MODULES).map(([k, v]) => [`\`${k}\``, v]))}

## Repos

${mdTable(['Repo', 'Owns'], Object.entries(DATA_REPOS).map(([k, v]) => [`\`${k}\``, v]))}

The Yjs document itself is persisted by the \`y-idb\` dependency (vrwarp fork)
into the separate \`versicle-yjs\` database; \`snapshot/YjsSnapshotService\`
is the one read/write/export surface over it.
`;
}

// ---------------------------------------------------------------------------
// src/domains/README.md
// ---------------------------------------------------------------------------

export function renderDomainsReadme(): string {
  const rows = Object.entries(DOMAIN_MODULES).map(([name, desc]) => [`\`${name}/\``, desc]);
  return `${generatedBanner()}
# Domains (L3) — vertical feature modules

Import discipline (master plan §2 rule 3, depcruise \`domains-no-store\` at
**error**/0): a domain may import \`kernel/\`, \`data/\`, its own module,
and other domains' published \`index.ts\` — never \`store/\`. Domains
declare \`ports.ts\` where they need state or platform services; \`app/\`
injects store-backed adapters (the EngineContext pattern generalized). The
one named carve-out: \`store/yjs-provider.ts\` for live Y.Doc handles
(checkpoints/inspector), named in the rule comment.

${mdTable(['Domain', 'What it owns'], rows)}

Published surfaces: \`chinese\`, \`google\`, \`library\`, \`search\`, and
\`sync\` export via their \`index.ts\` (rule 3's cross-domain door —
\`sync/index.ts\` currently has zero cross-domain consumers and is kept as
the contract surface). \`reader\` has no barrel: only \`app/\` composes it
(the composition root's privilege), and no other domain imports it.

**The audio domain is the honest geography exception:** it was rebuilt in
place across Phase 5 and lives at \`src/lib/tts/\` (engine/, providers/,
pipeline modules) with its app-side adapters at \`src/app/tts/\` — every
boundary rule applies to it by path-specific lint rules rather than a
\`domains/audio/\` address. Moving it is pure motion with no behavioral
payoff and was deliberately not done (master plan close-out).
`;
}
