/**
 * Display names for every rate pool, in dashboard order.
 *
 * This map — NOT the defaults table — is what the Quota & Usage list in
 * GenAISettingsTab iterates, so a pool with no entry here is invisible in
 * settings and can never be inspected or edited (pinned by
 * GenAISettingsTab.test.tsx). It lives in its own module so the tab file
 * stays component-only (react-refresh).
 */
export const RATE_POOL_LABELS: Record<string, string> = {
    default: 'Default / General',
    'gemini-1.5-pro': 'Gemini 1.5 Pro',
    // Text-out models
    'gemini-flash-lite-latest': 'Gemini Flash-Lite Latest (alias)',
    'gemini-2.0-flash': 'Gemini 2 Flash',
    'gemini-2.0-flash-lite': 'Gemini 2 Flash Lite',
    'gemini-2.5-flash': 'Gemini 2.5 Flash',
    'gemini-2.5-flash-lite': 'Gemini 2.5 Flash-Lite',
    'gemini-2.5-pro': 'Gemini 2.5 Pro',
    'gemini-3-flash-preview': 'Gemini 3 Flash',
    'gemini-3.1-flash-lite': 'Gemini 3.1 Flash Lite',
    'gemini-3.1-pro-preview': 'Gemini 3.1 Pro',
    'gemini-3.5-flash': 'Gemini 3.5 Flash',
    'gemini-3.5-flash-lite': 'Gemini 3.5 Flash Lite',
    'gemini-3.6-flash': 'Gemini 3.6 Flash',
    'gemini-3.7-flash': 'Gemini 3.7 Flash',
    'gemini-3.8-flash': 'Gemini 3.8 Flash',
    // Agents
    'antigravity-preview-05-2026': 'Antigravity',
    'deep-research-pro-preview-12-2025': 'Deep Research Pro Preview',
    // Multi-modal generative models
    'gemini-2.5-flash-image': 'Nano Banana (Gemini 2.5 Flash Image)',
    'gemini-2.5-flash-preview-tts': 'Gemini 2.5 Flash TTS',
    'gemini-2.5-pro-preview-tts': 'Gemini 2.5 Pro TTS',
    'gemini-3-pro-image': 'Nano Banana Pro (Gemini 3 Pro Image)',
    'gemini-3.1-flash-image': 'Nano Banana 2 (Gemini 3.1 Flash Image)',
    'gemini-3.1-flash-lite-image': 'Nano Banana 2 Lite (Gemini 3.1 Flash Lite Image)',
    'gemini-3.1-flash-tts-preview': 'Gemini 3.1 Flash TTS',
    'gemini-omni-flash-preview': 'Gemini Omni Flash',
    'gemini-omni-1.1-flash': 'Gemini Omni 1.1 Flash',
    'imagen-4.0-fast-generate-001': 'Imagen 4 Fast Generate',
    'imagen-4.0-generate-001': 'Imagen 4 Generate',
    'imagen-4.0-ultra-generate-001': 'Imagen 4 Ultra Generate',
    'lyria-3-clip-preview': 'Lyria 3 Clip',
    'lyria-3-pro-preview': 'Lyria 3 Pro',
    'veo-3.1-fast-generate-preview': 'Veo 3 Fast Generate',
    'veo-3.1-generate-preview': 'Veo 3 Generate',
    'veo-3.1-lite-generate-preview': 'Veo 3 Lite Generate',
    // Live API
    'gemini-2.5-flash-native-audio-preview-12-2025': 'Gemini 2.5 Flash Native Audio Dialog',
    'gemini-3.1-flash-live-preview': 'Gemini 3 Flash Live',
    'gemini-3.5-live-translate-preview': 'Gemini 3.5 Live Translate',
    'gemini-3.5-transcribe': 'Gemini 3.5 Transcribe',
    'gemini-3.5-transcribe-live': 'Gemini 3.5 Transcribe Live',
    'gemini-3.8-live': 'Gemini 3.8 Live',
    'gemini-3.8-live-extended-thinking': 'Gemini 3.8 Live Extended Thinking',
    // Other models
    'gemini-2.5-computer-use-preview-10-2025': 'Computer Use Preview',
    'gemini-embedding-001': 'Gemini Embedding 1',
    'gemini-embedding-2': 'Gemini Embedding 2',
    'gemini-robotics-er-1.5-preview': 'Gemini Robotics ER 1.5 Preview',
    'gemini-robotics-er-1.6-preview': 'Gemini Robotics ER 1.6 Preview',
    'gemini-robotics-er-2-preview': 'Gemini Robotics ER 2 Preview',
    'gemma-4-26b-a4b-it': 'Gemma 4 26B',
    'gemma-4-31b-it': 'Gemma 4 31B',
    'deep-research-pro-preview-map-grounding': 'Deep Research Pro Preview (Map Grounding)',
    'gemini-2-flash-map-grounding': 'Gemini 2 Flash (Map Grounding)',
    'gemini-2.0-flash-map-grounding': 'Gemini 2.0 Flash (Map Grounding)',
    'computer-use-preview-map-grounding': 'Computer Use Preview (Map Grounding)',
    'gemini-2.5-flash-map-grounding': 'Gemini 2.5 Flash (Map Grounding)',
    'gemini-2.5-flash-lite-map-grounding': 'Gemini 2.5 Flash Lite (Map Grounding)',
    'gemini-2.5-pro-map-grounding': 'Gemini 2.5 Pro (Map Grounding)',
    'gemini-3-flash-preview-map-grounding': 'Gemini 3 Flash (Map Grounding)',
    'gemini-3.1-pro-preview-map-grounding': 'Gemini 3.1 Pro (Map Grounding)',
    'gemini-3.1-flash-lite-map-grounding': 'Gemini 3.1 Flash Lite (Map Grounding)',
    'gemini-3.1-flash-tts-map-grounding': 'Gemini 3.1 Flash TTS (Map Grounding)',
    'gemini-3.5-flash-map-grounding': 'Gemini 3.5 Flash (Map Grounding)',
    'gemini-3.5-flash-lite-map-grounding': 'Gemini 3.5 Flash Lite (Map Grounding)',
    'gemini-3.5-transcribe-map-grounding': 'Gemini 3.5 Transcribe (Map Grounding)',
    'gemini-3.6-flash-map-grounding': 'Gemini 3.6 Flash (Map Grounding)',
    'gemini-3.7-flash-map-grounding': 'Gemini 3.7 Flash (Map Grounding)',
    'gemini-3.8-flash-map-grounding': 'Gemini 3.8 Flash (Map Grounding)',
    'gemini-robotics-er-1.6-preview-map-grounding': 'Gemini Robotics ER 1.6 Preview (Map Grounding)',
    'gemini-robotics-er-2-preview-map-grounding': 'Gemini Robotics ER 2 Preview (Map Grounding)',
    'gemini-2-search-grounding': 'Gemini 2 (Search Grounding)',
    'gemini-2.0-search-grounding': 'Gemini 2.0 (Search Grounding)',
    'gemini-2.5-search-grounding': 'Gemini 2.5 (Search Grounding)',
    'gemini-3-search-grounding': 'Gemini 3 (Search Grounding)',
    'default-search-grounding': 'Default (Search Grounding)',
    'google-tts': 'Google Text-to-Speech (Fallback)',
    'google-tts-chirp3-hd': 'Google TTS Chirp 3: HD',
    'google-tts-wavenet': 'Google TTS WaveNet',
    'google-tts-studio': 'Google TTS Studio',
    'google-tts-standard': 'Google TTS Standard',
    'google-tts-neural2': 'Google TTS Neural2',
    'google-tts-polyglot': 'Google TTS Polyglot (Preview)',
    'openai-tts': 'OpenAI Text-to-Speech',
};
